// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDmRK4PGvn_pfKgx1R4Ym5Cx1msQ7bRs',
    appId: '1:1064121685449:web:317f1a4f09f6cb90668418',
    messagingSenderId: '1064121685449',
    projectId: 'poker-dice-dash',
    authDomain: 'poker-dice-dash.firebaseapp.com',
    storageBucket: 'poker-dice-dash.firebasestorage.app',
    measurementId: 'G-K2XBKWRYNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBab9RSAhk-TfRIQaCYways5N67hG7uXsU',
    appId: '1:1064121685449:android:e135b320f388f4cd668418',
    messagingSenderId: '1064121685449',
    projectId: 'poker-dice-dash',
    storageBucket: 'poker-dice-dash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9j4bdxOyTKK5KdCmw99oX_eFzRQv8pRs',
    appId: '1:1064121685449:ios:1d273ae3e2813306668418',
    messagingSenderId: '1064121685449',
    projectId: 'poker-dice-dash',
    storageBucket: 'poker-dice-dash.firebasestorage.app',
    iosBundleId: 'com.example.pokerDiceDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9j4bdxOyTKK5KdCmw99oX_eFzRQv8pRs',
    appId: '1:1064121685449:ios:1d273ae3e2813306668418',
    messagingSenderId: '1064121685449',
    projectId: 'poker-dice-dash',
    storageBucket: 'poker-dice-dash.firebasestorage.app',
    iosBundleId: 'com.example.pokerDiceDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiDmRK4PGvn_pfKgx1R4Ym5Cx1msQ7bRs',
    appId: '1:1064121685449:web:176841da009a8579668418',
    messagingSenderId: '1064121685449',
    projectId: 'poker-dice-dash',
    authDomain: 'poker-dice-dash.firebaseapp.com',
    storageBucket: 'poker-dice-dash.firebasestorage.app',
    measurementId: 'G-HQ23K63T8M',
  );
}
